### ISSUE TITLE
Semi-Transparent Parts

### ISSUE THREAD

**Issue by TedThompson** [bigorangemachine/ksp-kronalutils#21]
The effect can be viewed in the following image

![](http://i.imgur.com/kC1zcsS.png)

If KVV is removed this effect is removed with it.  I don't know of anything required for this to happen beyond having KVV installed and using the 32 bit version of KSP.

Here are my system specs:
https://www.dropbox.com/s/dubd0jwrm4fo90n/TG626%20System%20Information.txt?dl=0

**Comment by bigorangemachine** [comment]
Was unable to confirm bug.

This commit caused some issues and needs tweaks.  In the future there needs to be a way to separate the preview model from the editor model.
