### ISSUE TITLE
Memory Leak - Not Removing Ship Shot From RAM

### ISSUE THREAD

**Issue by jediminer543** [bigorangemachine/ksp-kronalutils#29]
Just thought that i would point this out, after saving a screenshot it stays in memory.

Test showing Error (done with high res (2772x9216)):
Before pressing screenshot button: 2631MB
After taking screenshot: 2924MB

The image is probably stuck in memory and not properly deleted. Leaving the VAB and returning to the main menu don't remove it from the memory. The above test was performed on Windows 8.1.

**Comment by bigorangemachine** [comment]
[Duplicate Bug](https://github.com/bigorangemachine/ksp-kronalutils/issues/27)

**Comment by bigorangemachine** [comment]
@jediminer543 

Please try this [beta release](https://github.com/bigorangemachine/ksp-kronalutils/releases/tag/0.0.4%281.0.4%29beta)
