### ISSUE TITLE
Turning off FXAA changes outline from black to white

### ISSUE THREAD

**Issue by Kemp-J** [bigorangemachine/ksp-kronalutils#30]
As per title, if FXAA is disabled then the outline changes from black to white. I suspect this was not intended behaviour.

Use of AA on the outline and no option for setting background colour combine to make it hard to composite the image into another illustration. Turning off AA would normally be a solution except that this introduces the issue noted above.

Exporting onto transparent background would be ideal of course ;)

**Comment by Kemp-J** [comment]
I was mistaken. Turning off FXAA actually removes the outline and adds transparency around the edge of the ship. Not sure if this is intuitive behaviour, but my original report was incorrect so I've closed this report.

**Comment by bigorangemachine** [comment]
Cool thanks for the support!
