### ISSUE TITLE
Empty PNG with RealismOverhaul & RP-0 under 1.0.5

### ISSUE THREAD

**Issue by LZY-1006** [bigorangemachine/ksp-kronalutils#32]
With **RealismOverhaul** 10.9.6, **RP-0** 0.47 (newest up to 2016-4-16), & their dependencies (that do not seem very relevant) under 1.0.5, the **preview is fine**, but the **resulting PNG is empty** (0 byte), under offset mode or not, with the default settings. **Millions of similar log entries** are created through 7 seconds and freezes my Chrome browser when copied here completely, so I will append only several lines below:

`[LOG 17:50:23.295] awake
[LOG 17:50:23.414] [Warning] KRSVesselShotNo replacement for KSP/Alpha/Translucent (UnityEngine.Shader) in mk1pod (Part)/*/flagTransform (UnityEngine.MeshRenderer)
[LOG 17:50:23.416] [Warning] KRSVesselShotNo replacement for KSP/Alpha/Translucent Specular (UnityEngine.Shader) in mk1pod (Part)/*/Shine (UnityEngine.MeshRenderer)
[LOG 17:50:23.419] [Warning] KRSVesselShotNo replacement for KSP/Emissive/Diffuse (UnityEngine.Shader) in R7.Core.Engine (Part)/*/Cylinder_001 (UnityEngine.MeshRenderer)
[LOG 17:50:23.421] [Warning] KRSVesselShotNo replacement for KSP/Emissive/Diffuse (UnityEngine.Shader) in R7.Core.Engine (Part)/*/Cylinder_003 (UnityEngine.MeshRenderer)
[LOG 17:50:23.422] [Warning] KRSVesselShotNo replacement for KSP/Emissive/Diffuse (UnityEngine.Shader) in R7.Core.Engine (Part)/*/Cylinder_007 (UnityEngine.MeshRenderer)`

**(R7.\* & mk1pod are parts modified by RealismOverhaul & its dependency, Ven's Stock Revamp)**
[Uploading KVV Incompatible with RO.txt…]()

This is the craft in question:
`
[Vostok 1.txt](https://github.com/bigorangemachine/ksp-kronalutils/files/222232/Vostok.1.txt)
`

**Comment by LZY-1006** [comment]
Strangely, I **was able to render** a print for this craft **with a part from RP-0** in February:
![Uploading front_A-4_1.png…]()

**Comment by bigorangemachine** [comment]
Sorry thought this was closed.

There is currently an issue with shaders.  Going to close this as I am fairly certain its related to the 1.1.1 updated (I did have to recompile to get around these 0 size images).  I expect its related to the Unity5 update.
